export const SEENDO_DAILY_LIMIT = 20_000
export const SEENDO_RESTRICTED_THRESHOLD = 0.7
export const SEENDO_WINDOW_MS = 24 * 60 * 60 * 1000
export const SEENDO_GLOBAL_MONTHLY_LIMIT = 600_000
export const SEENDO_DAILY_CALL_LIMIT = 5
export const SEENDO_RESTRICTED_CALLS_THRESHOLD = 4
